# Header
menu:
  首页: /
  大数据: /categories/Big-Data
  编程: /categories/Programming
  全部文章: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
#- category
#- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-37223379-1
favicon: /favicon.png
twitter: zjerryj
google_plus: zhangji87@gmail.com
fb_admins:
fb_app_id:
